package com.mahnoosh.home.domain.model


data class Hour(
    val timeEpoch: Int,
    val time: String,
    val tempC: Double,
    val tempF: Double,
    val isDay: Int,
    val condition: Condition,
    val windMph: Double,
    val windKph: Double,
    val windDegree: Int,
    val windDir: String,
    val pressureMb: Int,
    val pressureIn: Double,
    val precipMm: Int,
    val precipIn: Int,
    val snowCm: Int,
    val humidity: Int,
    val cloud: Int,
    val feelslikeC: Double,
    val feelslikeF: Double,
    val windchillC: Double,
    val windchillF: Double,
    val heatindexC: Double,
    val heatindexF: Double,
    val dewpointC: Double,
    val dewpointF: Double,
    val willItRain: Int,
    val chanceOfRain: Int,
    val willItSnow: Int,
    val chanceOfSnow: Int,
    val visKm: Int,
    val visMiles: Int,
    val gustMph: Double,
    val gustKph: Double,
    val uv: Int,
    val shortRad: Int,
    val diffRad: Int,
    val dni: Int,
    val gti: Int
)